### ISSUE TITLE
Proposal for author | email | branch

### ISSUE THREAD

**Issue by monolithed** [michalbe/git-info#7]
Maybe you should use the following rules?

```
author => git config --get user.name
email => git config --get user.email
branch => git rev-parse --abbrev-ref HEAD
```

I think it will be more correct and productive

**Comment by michalbe** [comment]
@monolithed do you have one now :)?

**Comment by michalbe** [comment]
@monolithed or now :)?

**Comment by monolithed** [comment]
@michalbe after 3 years I don't even remember the problem for why I needed it ))

**Comment by michalbe** [comment]
@monolithed ok, closing this then.
